# Your Solution
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
     - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL = postgresql://varsha_task72c_user:FfZ5uRByk6UXXfo8pncYPopEnSJZgsoz@dpg-crmo9iq3esus7380rlrg-a.oregon-postgres.render.com/varsha_task72c

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL = postgresql://varsha_task72c_user:FfZ5uRByk6UXXfo8pncYPopEnSJZgsoz@dpg-crmo9iq3esus7380rlrg-a.oregon-postgres.render.com/varsha_task72c

