version: '3.8'
services:
  book_catalog:
    build: ./book_catalog
    ports:
      - "3001:8000"  # Map host port 3001 to container port 8000
    environment:
      DATABASE_URL: "postgresql://project_part3_lebe_user:qsTRAQ7P79IsjJFMgoDuGXWTNycbA4Rk@dpg-crn5v868ii6s73el93m0-a.oregon-postgres.render.com/project_part3_lebe"

  inventory_management:
    build: ./inventory_management
    ports:
      - "3002:8000"  # Map host port 3002 to container port 8000
    environment:
      DATABASE_URL: "postgresql://project_part3_lebe_user:qsTRAQ7P79IsjJFMgoDuGXWTNycbA4Rk@dpg-crn5v868ii6s73el93m0-a.oregon-postgres.render.com/project_part3_lebe"